/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IFeeDistributor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFeeDistributor__factory>
getContractFactory(name: 'MetaPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaPool__factory>
getContractFactory(name: 'IMetaPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IMetaPool__factory>
getContractFactory(name: 'IOperatorRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOperatorRegistry__factory>
getContractFactory(name: 'MetaPoolDisputeResolver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaPoolDisputeResolver__factory>
getContractFactory(name: 'MockFeeDistributor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockFeeDistributor__factory>
getContractFactory(name: 'MockOperatorRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockOperatorRegistry__factory>

  getContractAt(name: 'IFeeDistributor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFeeDistributor>
getContractAt(name: 'MetaPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaPool>
getContractAt(name: 'IMetaPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IMetaPool>
getContractAt(name: 'IOperatorRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOperatorRegistry>
getContractAt(name: 'MetaPoolDisputeResolver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaPoolDisputeResolver>
getContractAt(name: 'MockFeeDistributor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockFeeDistributor>
getContractAt(name: 'MockOperatorRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockOperatorRegistry>

  deployContract(name: 'IFeeDistributor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeDistributor>
deployContract(name: 'MetaPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaPool>
deployContract(name: 'IMetaPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMetaPool>
deployContract(name: 'IOperatorRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOperatorRegistry>
deployContract(name: 'MetaPoolDisputeResolver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaPoolDisputeResolver>
deployContract(name: 'MockFeeDistributor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFeeDistributor>
deployContract(name: 'MockOperatorRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOperatorRegistry>

  deployContract(name: 'IFeeDistributor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeDistributor>
deployContract(name: 'MetaPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaPool>
deployContract(name: 'IMetaPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IMetaPool>
deployContract(name: 'IOperatorRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOperatorRegistry>
deployContract(name: 'MetaPoolDisputeResolver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaPoolDisputeResolver>
deployContract(name: 'MockFeeDistributor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockFeeDistributor>
deployContract(name: 'MockOperatorRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockOperatorRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  