/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockFeeDistributor } from './MockFeeDistributor.js';
export type { MockOperatorRegistry } from './MockOperatorRegistry.js';