/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMetaPool, IMetaPoolInterface } from "../../MetaPoolDisputeResolver.sol/IMetaPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "marketId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "disputant",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "accepted",
        "type": "bool"
      }
    ],
    "name": "resolveDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "marketId",
        "type": "uint256"
      },
      {
        "internalType": "enum IMetaPool.MarketOutcome",
        "name": "newOutcome",
        "type": "uint8"
      }
    ],
    "name": "resolveReview",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMetaPool__factory {
    static readonly abi = _abi;
    static createInterface(): IMetaPoolInterface {
      return new Interface(_abi) as IMetaPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMetaPool {
      return new Contract(address, _abi, runner) as unknown as IMetaPool;
    }
  }
  