/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IOperatorRegistry, IOperatorRegistryInterface } from "../../MetaPoolDisputeResolver.sol/IOperatorRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "serviceId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      }
    ],
    "name": "getOperator",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "stake",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "unstakeRequestTime",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "serviceId",
        "type": "uint256"
      }
    ],
    "name": "operatorCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IOperatorRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IOperatorRegistryInterface {
      return new Interface(_abi) as IOperatorRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IOperatorRegistry {
      return new Contract(address, _abi, runner) as unknown as IOperatorRegistry;
    }
  }
  