/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMetaPoolInterface extends Interface {
    getFunction(nameOrSignature: "resolveDispute" | "resolveReview"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'resolveReview', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveReview', data: BytesLike): Result;
  }

  

  export interface IMetaPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMetaPool;
    waitForDeployment(): Promise<this>;

    interface: IMetaPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    resolveDispute: TypedContractMethod<
      [marketId: BigNumberish, disputant: AddressLike, accepted: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    resolveReview: TypedContractMethod<
      [marketId: BigNumberish, newOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [marketId: BigNumberish, disputant: AddressLike, accepted: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveReview'): TypedContractMethod<
      [marketId: BigNumberish, newOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }