/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IOperatorRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getOperator" | "operatorCount"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getOperator', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'operatorCount', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorCount', data: BytesLike): Result;
  }

  

  export interface IOperatorRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IOperatorRegistry;
    waitForDeployment(): Promise<this>;

    interface: IOperatorRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getOperator: TypedContractMethod<
      [serviceId: BigNumberish, operator: AddressLike, ],
      [[bigint, bigint, boolean] & {stake: bigint, unstakeRequestTime: bigint, active: boolean }],
      'view'
    >
    

    
    operatorCount: TypedContractMethod<
      [serviceId: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getOperator'): TypedContractMethod<
      [serviceId: BigNumberish, operator: AddressLike, ],
      [[bigint, bigint, boolean] & {stake: bigint, unstakeRequestTime: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'operatorCount'): TypedContractMethod<
      [serviceId: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }