/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MetaPoolDisputeResolverInterface extends Interface {
    getFunction(nameOrSignature: "disputeTally" | "disputeVoted" | "metaPool" | "operatorCount" | "owner" | "registry" | "renounceOwnership" | "reviewExecuted" | "reviewVoted" | "reviewVotes" | "serviceId" | "transferOwnership" | "voteDispute" | "voteReview"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeExecuted" | "DisputeVoteCast" | "OwnershipTransferred" | "ReviewExecuted" | "ReviewVoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'disputeTally', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'disputeVoted', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'metaPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'operatorCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reviewExecuted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reviewVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'reviewVotes', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'serviceId', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voteDispute', values: [BigNumberish, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'voteReview', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'disputeTally', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'metaPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewExecuted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reviewVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'serviceId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteReview', data: BytesLike): Result;
  }

  
    export namespace DisputeExecutedEvent {
      export type InputTuple = [marketId: BigNumberish, disputant: AddressLike, accepted: boolean];
      export type OutputTuple = [marketId: bigint, disputant: string, accepted: boolean];
      export interface OutputObject {marketId: bigint, disputant: string, accepted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeVoteCastEvent {
      export type InputTuple = [marketId: BigNumberish, disputant: AddressLike, operator: AddressLike, accept: boolean];
      export type OutputTuple = [marketId: bigint, disputant: string, operator: string, accept: boolean];
      export interface OutputObject {marketId: bigint, disputant: string, operator: string, accept: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewExecutedEvent {
      export type InputTuple = [marketId: BigNumberish, outcome: BigNumberish];
      export type OutputTuple = [marketId: bigint, outcome: bigint];
      export interface OutputObject {marketId: bigint, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReviewVoteCastEvent {
      export type InputTuple = [marketId: BigNumberish, operator: AddressLike, outcome: BigNumberish];
      export type OutputTuple = [marketId: bigint, operator: string, outcome: bigint];
      export interface OutputObject {marketId: bigint, operator: string, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MetaPoolDisputeResolver extends BaseContract {
    
    connect(runner?: ContractRunner | null): MetaPoolDisputeResolver;
    waitForDeployment(): Promise<this>;

    interface: MetaPoolDisputeResolverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    disputeTally: TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, boolean] & {acceptVotes: bigint, rejectVotes: bigint, executed: boolean }],
      'view'
    >
    

    
    disputeVoted: TypedContractMethod<
      [arg0: BytesLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    metaPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    operatorCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reviewExecuted: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    reviewVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    reviewVotes: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    serviceId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    voteDispute: TypedContractMethod<
      [marketId: BigNumberish, disputant: AddressLike, accept: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    voteReview: TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'disputeTally'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[bigint, bigint, boolean] & {acceptVotes: bigint, rejectVotes: bigint, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'disputeVoted'): TypedContractMethod<
      [arg0: BytesLike, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'metaPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'operatorCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reviewExecuted'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reviewVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reviewVotes'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'serviceId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteDispute'): TypedContractMethod<
      [marketId: BigNumberish, disputant: AddressLike, accept: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteReview'): TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeExecuted'): TypedContractEvent<DisputeExecutedEvent.InputTuple, DisputeExecutedEvent.OutputTuple, DisputeExecutedEvent.OutputObject>;
getEvent(key: 'DisputeVoteCast'): TypedContractEvent<DisputeVoteCastEvent.InputTuple, DisputeVoteCastEvent.OutputTuple, DisputeVoteCastEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ReviewExecuted'): TypedContractEvent<ReviewExecutedEvent.InputTuple, ReviewExecutedEvent.OutputTuple, ReviewExecutedEvent.OutputObject>;
getEvent(key: 'ReviewVoteCast'): TypedContractEvent<ReviewVoteCastEvent.InputTuple, ReviewVoteCastEvent.OutputTuple, ReviewVoteCastEvent.OutputObject>;

    filters: {
      
      'DisputeExecuted(uint256,address,bool)': TypedContractEvent<DisputeExecutedEvent.InputTuple, DisputeExecutedEvent.OutputTuple, DisputeExecutedEvent.OutputObject>;
      DisputeExecuted: TypedContractEvent<DisputeExecutedEvent.InputTuple, DisputeExecutedEvent.OutputTuple, DisputeExecutedEvent.OutputObject>;
    

      'DisputeVoteCast(uint256,address,address,bool)': TypedContractEvent<DisputeVoteCastEvent.InputTuple, DisputeVoteCastEvent.OutputTuple, DisputeVoteCastEvent.OutputObject>;
      DisputeVoteCast: TypedContractEvent<DisputeVoteCastEvent.InputTuple, DisputeVoteCastEvent.OutputTuple, DisputeVoteCastEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ReviewExecuted(uint256,uint8)': TypedContractEvent<ReviewExecutedEvent.InputTuple, ReviewExecutedEvent.OutputTuple, ReviewExecutedEvent.OutputObject>;
      ReviewExecuted: TypedContractEvent<ReviewExecutedEvent.InputTuple, ReviewExecutedEvent.OutputTuple, ReviewExecutedEvent.OutputObject>;
    

      'ReviewVoteCast(uint256,address,uint8)': TypedContractEvent<ReviewVoteCastEvent.InputTuple, ReviewVoteCastEvent.OutputTuple, ReviewVoteCastEvent.OutputObject>;
      ReviewVoteCast: TypedContractEvent<ReviewVoteCastEvent.InputTuple, ReviewVoteCastEvent.OutputTuple, ReviewVoteCastEvent.OutputObject>;
    
    };
  }