/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockFeeDistributor, MockFeeDistributorInterface } from "../../mocks/MockFeeDistributor.js";

  const _abi = [
  {
    "inputs": [],
    "name": "depositCalls",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "depositFee",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "totalReceived",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x60808060405234601557610108908161001b8239f35b600080fdfe608060405260043610156026575b3615601757600080fd5b60213460005460c6565b600055005b60003560e01c806367a52793146086578063a3c2c46214606a5763ee694c1a03600d573460655760003660031901126065576020600154604051908152f35b600080fd5b3460655760003660031901126065576020600054604051908152f35b6000366003190112606557609b3460005460c6565b6000556001546001810180911160b057600155005b634e487b7160e01b600052601160045260246000fd5b9190820180921160b05756fea2646970667358221220c6cd04dd26b32aa42d46bcc38b4eb70537799e40c4dbc185a608612ffed1a38964736f6c634300081b0033";

  
      type MockFeeDistributorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockFeeDistributorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockFeeDistributor__factory extends ContractFactory {
    
      constructor(...args: MockFeeDistributorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockFeeDistributor & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockFeeDistributor__factory {
      return super.connect(runner) as MockFeeDistributor__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockFeeDistributorInterface {
      return new Interface(_abi) as MockFeeDistributorInterface;
    }
    
    override attach(address: string | Addressable): MockFeeDistributor {
      return super.attach(address) as MockFeeDistributor;
    }
  static connect(address: string, runner?: ContractRunner | null): MockFeeDistributor {
      return new Contract(address, _abi, runner) as unknown as MockFeeDistributor;
    }
  }

  
  