/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockOperatorRegistry, MockOperatorRegistryInterface } from "../../mocks/MockOperatorRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "serviceId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "op",
        "type": "address"
      }
    ],
    "name": "getOperator",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "stake",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "unstakeRequestTime",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isActive",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "operatorCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "serviceId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "op",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "name": "setOperator",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601557610296908161001b8239f35b600080fdfe6080604052600436101561001257600080fd5b60003560e01c806316d4b2ed14610144578063bab0ac03146100f7578063d07343ea146100cb5763d63204741461004857600080fd5b346100c65760403660031901126100c65761006161024a565b600435600052600060205260406000209060018060a01b0316600052602052606060ff60406000205416806000146100be57670de0b6b3a7640000905b67ffffffffffffffff604051921682526000602083015215156040820152f35b60009061009e565b600080fd5b346100c65760203660031901126100c65760043560005260016020526020604060002054604051908152f35b346100c65760403660031901126100c65761011061024a565b600435600052600060205260406000209060018060a01b0316600052602052602060ff604060002054166040519015158152f35b346100c65760603660031901126100c65760043561016061024a565b6044359182158015938481036100c6576000838152602081815260408083206001600160a01b038816845290915290205460ff169080610242575b610220575b81610218575b506101df575b600052600060205260406000209060018060a01b031660005260205260406000209060ff80198354169116179055600080f35b8060005260016020526040600020805490600019820191821161020257556101ac565b634e487b7160e01b600052601160045260246000fd5b9050846101a6565b82600052600160205260406000208054906001820180921161020257556101a0565b50801561019b565b602435906001600160a01b03821682036100c65756fea2646970667358221220b0ee7f082497ebf266c553dde7bf38afdb20f551731d7f399191c9a3561840ad64736f6c634300081b0033";

  
      type MockOperatorRegistryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockOperatorRegistryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockOperatorRegistry__factory extends ContractFactory {
    
      constructor(...args: MockOperatorRegistryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockOperatorRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockOperatorRegistry__factory {
      return super.connect(runner) as MockOperatorRegistry__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockOperatorRegistryInterface {
      return new Interface(_abi) as MockOperatorRegistryInterface;
    }
    
    override attach(address: string | Addressable): MockOperatorRegistry {
      return super.attach(address) as MockOperatorRegistry;
    }
  static connect(address: string, runner?: ContractRunner | null): MockOperatorRegistry {
      return new Contract(address, _abi, runner) as unknown as MockOperatorRegistry;
    }
  }

  
  